apiVersion: v1
kind: Secret
metadata:
  name: opendraw-secrets
type: Opaque # Opaque is the most common type of secret
data:
  # Base64 encoded values
  OPENAI_API_KEY: c2stcHJvai1IS3JadWV5d2J0ZWowU2dBN0VlTVQzQmxia0ZKdzdManZWRUVFd0JDT09KaVFGQ3I=