apiVersion: v1
kind: Secret
metadata:
  name: opendraw-secrets
type: Opaque # Opaque is the most common type of secret
data:
  # Base64 encoded values
  OPENAI_API_KEY: insert here key
  SECRET_KEY: dGVzdF9zZWNyZXRfa2V5XzEyMzQ1Njcw
  MONGO_USER: cm9vdA==
  MONGO_PASSWORD: cm9vdA==
